"""
GitHub Discovery — auto-discovers repos from a GitHub org/user and groups them
into logical projects by name prefix.

Grouping rule: a "project" is the longest common prefix shared by 2+ repos that
ends at a hyphen. Single-repo "projects" are still registered with the repo
name as the project_id.

Examples:
  billing-api, billing-frontend, billing-worker  → project "billing" (3 repos)
  conduit-django-api, conduit-react-ui           → project "conduit" (2 repos)
  hello-world                                     → project "hello-world" (1 repo, no group)

No filtering: includes forks and archived repos per your config choice.
"""

import os
import re
import logging
from typing import Optional
from collections import defaultdict
import requests
from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger(__name__)

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_OWNER = os.getenv("GITHUB_REPO_OWNER", "AkashW45")
GH_API = "https://api.github.com"

from agents.github_auth import get_github_headers
import os
import logging

logger = logging.getLogger(__name__)

import os
import logging

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────
# Dynamic exclusion: heuristics + GitHub topics + DB overrides
# ─────────────────────────────────────────────────────────────────────

# Regex patterns for names that almost always indicate junk. Tunable via env var.
_DEFAULT_JUNK_PATTERNS = [
    r"^test-",                          # test repos
    r"^demo$|^demo-",                   # demo repos
    r"^scratch-",                       # scratch work
    r"^tmp-|^temp-",                    # temporary
    r"^make-a-",                        # pipeline-generated by your own tool
    r"-hello-world($|-)",               # hello-world spam
    r"^playground-|^sandbox-",          # exploration repos
]

# Repos with these GitHub topics are always included regardless of heuristics
TOPIC_INCLUDE = "sdlc-include"
# Repos with this topic are always excluded
TOPIC_EXCLUDE = "sdlc-exclude"

# Minimum repo size in KB for default inclusion. Smaller-than-this with no
# description gets filtered as "probably empty/junk". Override via env var.
MIN_REPO_SIZE_KB = int(os.getenv("DISCOVERY_MIN_REPO_KB", "5"))

# Whether to include forks and archived repos. Defaults match your earlier choice.
INCLUDE_FORKS = os.getenv("DISCOVERY_INCLUDE_FORKS", "true").lower() == "true"
INCLUDE_ARCHIVED = os.getenv("DISCOVERY_INCLUDE_ARCHIVED", "true").lower() == "true"

# Always exclude the platform's own repos (these are infrastructure, not products)
# Self-detected from env so it adapts if you rename the repo
PLATFORM_SELF_REPOS = {
    s.strip() for s in os.getenv("PLATFORM_SELF_REPOS", "SDLC,SDLC-V2,SDLC-V2-Clean").split(",")
    if s.strip()
}


def _load_db_overrides() -> dict:
    """
    Read user-set per-repo overrides from PostgreSQL.
    Returns: {repo_name: "include"|"exclude"}
    Fails open — if DB unavailable, returns empty dict.
    """
    try:
        from core.db_clients import pg_conn
        with pg_conn() as conn:
            cur = conn.cursor()
            # Idempotent — creates table on first call so this just works
            cur.execute("""
                        CREATE TABLE IF NOT EXISTS repo_overrides (
                                                                      repo_name VARCHAR(255) PRIMARY KEY,
                            action VARCHAR(20) NOT NULL,  -- 'include' or 'exclude'
                            reason TEXT,
                            set_by VARCHAR(255),
                            set_at TIMESTAMP DEFAULT NOW()
                            )
                        """)
            cur.execute("SELECT repo_name, action FROM repo_overrides")
            overrides = {row[0]: row[1] for row in cur.fetchall()}
            cur.close()
        return overrides
    except Exception as e:
        logger.warning(f"[GitHubDiscovery] repo_overrides lookup failed: {e}")
        return {}


def _matches_junk_pattern(name: str) -> Optional[str]:
    """Returns the pattern that matched, or None."""
    import re
    name_lower = name.lower()
    for pattern in _DEFAULT_JUNK_PATTERNS:
        if re.search(pattern, name_lower):
            return pattern
    return None

def _should_include_repo(repo: dict, overrides: dict) -> tuple[bool, str]:
    """
    Production policy: include every repo. The only opt-out is an explicit
    'exclude' override in the repo_overrides table.
    """
    if overrides.get(repo["name"]) == "exclude":
        return False, "db_override:exclude"
    return True, "included"
    # def _should_include_repo(repo: dict, overrides: dict) -> tuple[bool, str]:
    #     """
    #     Decide whether to include a repo. Returns (include?, reason).
    #     Order of precedence:
    #       1. Database override (manual decision wins)
    #       2. GitHub topic 'sdlc-include' or 'sdlc-exclude'
    #       3. Platform self-repos (always excluded)
    #       4. Heuristics (size, name patterns, description)
    #     """
    #     name = repo["name"]
    #     topics = repo.get("topics", []) or []

    #     # 1. Manual DB override — highest priority
    #     if name in overrides:
    #         action = overrides[name]
    #         return (action == "include"), f"db_override:{action}"

    #     # 2. GitHub topic opt-in/opt-out — declarative, lives in GitHub itself
    #     if TOPIC_EXCLUDE in topics:
    #         return False, f"topic:{TOPIC_EXCLUDE}"
    #     if TOPIC_INCLUDE in topics:
    #         return True, f"topic:{TOPIC_INCLUDE}"

    #     # 3. Platform self-repos
    #     if name in PLATFORM_SELF_REPOS:
    #         return False, "platform_self_repo"

    #     # 4. Fork / archived policy
    #     if repo.get("fork") and not INCLUDE_FORKS:
    #         return False, "fork_excluded_by_policy"
    #     if repo.get("archived") and not INCLUDE_ARCHIVED:
    #         return False, "archived_excluded_by_policy"

    #     # 5. Junk name patterns
    #     pattern_match = _matches_junk_pattern(name)
    #     if pattern_match:
    #         return False, f"junk_pattern:{pattern_match}"

    #     # 6. Empty / abandoned heuristic — small size AND no description
    #     size_kb = repo.get("size_kb", 0)
    #     desc = (repo.get("description") or "").strip()
    #     if size_kb < MIN_REPO_SIZE_KB and not desc:
    #         return False, f"empty_repo:size={size_kb}KB_no_desc"

    return True, "included"
# ─────────────────────────────────────────────────────────────────────
# 1. List repos from GitHub
# ─────────────────────────────────────────────────────────────────────
def _is_org(owner: str) -> bool:
    """Detect whether owner is a User or Organization. Affects API endpoint."""
    r = requests.get(f"{GH_API}/users/{owner}", headers=get_github_headers(), timeout=10)
    if r.status_code == 200:
        return r.json().get("type") == "Organization"
    return False


def list_all_repos(owner: Optional[str] = None) -> list:
    """
    Return ALL repos accessible to the GitHub App installation (public + private).
    Uses /installation/repositories endpoint which respects App scope correctly.
    Falls back to /users/{owner}/repos for public-only if App auth unavailable.
    """
    from agents.github_auth import get_github_headers, GITHUB_APP_INSTALLATION_ID

    repos = []
    page = 1

    # ── Path A: GitHub App installation endpoint (sees private repos) ──
    if GITHUB_APP_INSTALLATION_ID:
        while True:
            params = {"per_page": 100, "page": page}
            r = requests.get(
                f"{GH_API}/installation/repositories",
                headers=get_github_headers(),
                params=params,
                timeout=15,
            )
            if r.status_code != 200:
                logger.error(f"[GitHubDiscovery] installation repos failed: {r.status_code} {r.text[:200]}")
                break

            data = r.json()
            batch = data.get("repositories", [])
            if not batch:
                break

            for repo in batch:
                repos.append({
                    "name": repo["name"],
                    "full_name": repo["full_name"],
                    "url": repo["clone_url"],
                    "ssh_url": repo.get("ssh_url"),
                    "html_url": repo["html_url"],
                    "description": repo.get("description") or "",
                    "language": repo.get("language") or "",
                    "topics": repo.get("topics", []),
                    "fork": bool(repo.get("fork")),
                    "archived": bool(repo.get("archived")),
                    "private": bool(repo.get("private")),
                    "default_branch": repo.get("default_branch", "main"),
                    "pushed_at": repo.get("pushed_at"),
                    "stargazers_count": repo.get("stargazers_count", 0),
                    "size_kb": repo.get("size", 0),
                })

            total = data.get("total_count", 0)
            logger.info(f"[GitHubDiscovery] page {page}: {len(batch)} repos (total={total})")

            if len(repos) >= total or len(batch) < 100:
                break
            page += 1

        logger.info(f"[GitHubDiscovery] found {len(repos)} repos via App installation")
        return repos

    # ── Path B: fallback — public repos only via user API ──
    owner = owner or GITHUB_OWNER
    logger.warning("[GitHubDiscovery] No App installation ID — falling back to public repos only")
    while True:
        params = {"per_page": 100, "page": page, "type": "all", "sort": "full_name"}
        r = requests.get(
            f"{GH_API}/users/{owner}/repos",
            headers=get_github_headers(),
            params=params,
            timeout=15,
        )
        if r.status_code != 200:
            break
        batch = r.json()
        if not batch:
            break
        for repo in batch:
            repos.append({
                "name": repo["name"],
                "full_name": repo["full_name"],
                "url": repo["clone_url"],
                "ssh_url": repo.get("ssh_url"),
                "html_url": repo["html_url"],
                "description": repo.get("description") or "",
                "language": repo.get("language") or "",
                "topics": repo.get("topics", []),
                "fork": bool(repo.get("fork")),
                "archived": bool(repo.get("archived")),
                "private": bool(repo.get("private")),
                "default_branch": repo.get("default_branch", "main"),
                "pushed_at": repo.get("pushed_at"),
                "size_kb": repo.get("size", 0),
            })
        if len(batch) < 100:
            break
        page += 1

    logger.info(f"[GitHubDiscovery] found {len(repos)} public repos via user API")
    return repos


# ─────────────────────────────────────────────────────────────────────
# 2. Group repos by name prefix
# ─────────────────────────────────────────────────────────────────────
def _split_prefix(name: str) -> str:
    """
    Extract the project prefix from a repo name.

    Rules:
      - Split on first hyphen: 'billing-api'  → 'billing'
      - If no hyphen, the whole name is the prefix: 'monorepo' → 'monorepo'
      - Lowercase, strip non-alphanumerics from the prefix end
    """
    base = re.split(r"[-_]", name, maxsplit=1)[0]
    base = re.sub(r"[^a-z0-9]+$", "", base.lower())
    return base or name.lower()


def group_repos_by_prefix(repos: list, min_group_size: int = 2) -> list:
    """
    Group repos by name prefix into project candidates.

    A prefix shared by >= min_group_size repos becomes a multi-repo project.
    A prefix with only 1 repo stays as a single-repo project (project_id == repo name).

    Returns: list of project dicts ready for register_project().
    """
    overrides = _load_db_overrides()
    kept = []
    filtered = []
    for r in repos:
        include, reason = _should_include_repo(r, overrides)
        if include:
            kept.append(r)
        else:
            filtered.append({"name": r["name"], "reason": reason})

    if filtered:
        logger.info(f"[GitHubDiscovery] filtered out {len(filtered)} repo(s):")
        for f in filtered:
            logger.info(f"  - {f['name']:40} ({f['reason']})")

    by_prefix = defaultdict(list)
    for repo in kept:
        prefix = _split_prefix(repo["name"])
        by_prefix[prefix].append(repo)

    projects = []
    for prefix, group in by_prefix.items():
        if len(group) >= min_group_size:
            # Multi-repo project
            techs = sorted({r["language"] for r in group if r["language"]})
            descs = [r["description"] for r in group if r["description"]]
            combined_desc = (
                " | ".join(descs)[:500]
                if descs
                else f"Repos grouped under prefix '{prefix}': "
                     f"{', '.join(r['name'] for r in group)}"
            )
            projects.append({
                "project_id": prefix,
                "project_name": prefix.replace("-", " ").title(),
                "description": combined_desc,
                "domain": "",  # unknown — humans can edit later
                "tech_stack": techs,
                "owner_team": "",
                "repos": [
                    {
                        "name": r["name"],
                        "url": r["url"],
                        "type": _infer_repo_type(r["name"]),
                        "branch": r["default_branch"],
                    }
                    for r in group
                ],
                "_meta": {
                    "fork_count": sum(1 for r in group if r["fork"]),
                    "archived_count": sum(1 for r in group if r["archived"]),
                    "languages": techs,
                },
            })
        else:
            # Single-repo project — register with repo name as project_id
            r = group[0]
            projects.append({
                "project_id": r["name"],
                "project_name": r["name"].replace("-", " ").title(),
                "description": r["description"] or f"GitHub repo {r['full_name']}",
                "domain": "",
                "tech_stack": [r["language"]] if r["language"] else [],
                "owner_team": "",
                "repos": [{
                    "name": r["name"],
                    "url": r["url"],
                    "type": _infer_repo_type(r["name"]),
                    "branch": r["default_branch"],
                }],
                "_meta": {
                    "fork": r["fork"],
                    "archived": r["archived"],
                    "language": r["language"],
                },
            })

    projects.sort(key=lambda p: p["project_id"])
    logger.info(f"[GitHubDiscovery] grouped {len(repos)} repos into {len(projects)} project(s)")
    return projects


def _infer_repo_type(name: str) -> str:
    n = name.lower()
    if any(s in n for s in ("frontend", "-ui", "-web", "react", "vue", "angular")):
        return "frontend"
    if any(s in n for s in ("backend", "-api", "-service", "-server")):
        return "backend"
    if any(s in n for s in ("worker", "-job", "-batch", "-consumer")):
        return "worker"
    if any(s in n for s in ("lib", "shared", "common", "sdk")):
        return "library"
    if any(s in n for s in ("infra", "iac", "terraform", "k8s", "kube")):
        return "infra"
    return "backend"


# ─────────────────────────────────────────────────────────────────────
# 3. End-to-end discover-and-preview
# ─────────────────────────────────────────────────────────────────────
def discover_projects(owner: Optional[str] = None,
                      min_group_size: int = 2) -> dict:
    """Returns project groupings plus visibility into what was filtered."""
    repos = list_all_repos(owner=owner)
    overrides = _load_db_overrides()

    kept = []
    filtered = []
    for r in repos:
        include, reason = _should_include_repo(r, overrides)
        if include:
            kept.append(r)
        else:
            filtered.append({"name": r["name"], "reason": reason})

    projects = group_repos_by_prefix(kept, min_group_size=min_group_size)
    return {
        "owner": owner or GITHUB_OWNER,
        "total_repos_in_github": len(repos),
        "total_repos_after_filter": len(kept),
        "total_projects": len(projects),
        "filtered_out": filtered,
        "projects": projects,
        "repos": kept,
    }